name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for production
      run: npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_PROD }}
        
    - name: Deploy to hosting service
      run: |
        echo "Add your deployment commands here"
        echo "Build completed successfully for production deployment"
        # Example for different hosting services:
        # Netlify: npx netlify-cli deploy --prod --dir=build
        # Vercel: npx vercel --prod
        # AWS S3: aws s3 sync build/ s3://your-bucket-name
        # GitHub Pages: Use actions/deploy-pages@v2
