name: Repository Health Check

on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=high
      continue-on-error: true
      
    - name: Check for outdated packages
      run: npm outdated
      continue-on-error: true
      
    - name: Repository health summary
      run: |
        echo "Repository Health Report" >> $GITHUB_STEP_SUMMARY
        echo "Check date: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "Dependencies checked" >> $GITHUB_STEP_SUMMARY
        echo "Security audit completed" >> $GITHUB_STEP_SUMMARY
